HANDALING IMBALANCED DATASET

1 Up Sampling

2 Down Sampling

In [1]:
import numpy as np
import pandas as pd

## Set the random seed for reproducibility
np.random.seed(123)


## Create a DataFrame with two class
n_Samples=1000
class_0_ratio=0.9
n_class_0=int(n_Samples*class_0_ratio)
n_class_1=n_Samples-n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [3]:
## Create my Dataframe with imbalance dataset
class_0=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})

class_1=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [4]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [5]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [6]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [7]:
##Up sampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [11]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, ##Sample with replacement
                               n_samples=len(df_majority),
                               random_state=42
                               )

In [12]:
df_minority_upsampled.shape

(900, 3)

In [13]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951  -0.874146  -0.156083       1
992   0.196570  -0.602575       1
914  -0.067830   0.998053       1
971   0.272825   1.034197       1
960   0.870056  -0.449515       1

In [14]:
df=df_upsample=pd.concat([df_majority,df_minority_upsampled])

In [15]:
df['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [16]:
## Down Sampling
import numpy as np
import pandas as pd

## Set the random seed for reproducibility
np.random.seed(123)


## Create a DataFrame with two class
n_Samples=1000
class_0_ratio=0.9
n_class_0=int(n_Samples*class_0_ratio)
n_class_1=n_Samples-n_class_0


## Create my Dataframe with imbalance dataset
class_0=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_0),
    'target':[0]*n_class_0
})

class_1=pd.DataFrame({
    'feature_1':np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=0,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})



df=pd.concat([class_0,class_1]).reset_index(drop=True)

##Check the class distribution

print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [17]:
##Down sampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [22]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False,
                               n_samples=len(df_minority),
                               random_state=42
                               )

In [23]:
df_majority_downsampled.shape

(100, 3)

In [24]:
df_majority_downsampled.head()

     feature_1  feature_2  target
70    0.468439   1.720920       0
827   1.089165  -0.464899       0
231   0.753869  -0.969798       0
588   0.588686  -0.704720       0
39    0.283627   1.012868       0

In [30]:
df_down=pd.concat([df_minority,df_majority_downsampled])

In [31]:
df_down['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64