Label Encoding

Label encoding and ordinal encoding are two techniques used to encode categorical data as numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable “color” with three possible values (red, green, blue), we can represent it using label encoding as follows:

1. Red: 1

2. Green: 2

3. Blue: 3

In [1]:
import pandas as pd

In [2]:
## Creating dataframe

df=pd.DataFrame({
    'color':['red','blue','gree','gree','red','blue']

})
df.head()

  color
0   red
1  blue
2  gree
3  gree
4   red

In [ ]:
## Label encoding
from sklearn.preprocessing import LabelEncoder

##Creating an instance variable by label Encoding
label_encoder=LabelEncoder()



##Perform fit and transform
label_encoder.fit_transform(df[['color']])

c:\Users\amitk\OneDrive\Desktop\complete data analyst bootcamp\venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [5]:
label_encoder.transform([['red']])

c:\Users\amitk\OneDrive\Desktop\complete data analyst bootcamp\venv\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

Ordinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking.
In this technique, each category is assigned a numerical value based on its position in the order.

For example, if we have a categorical variable “education level” with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High school: 1

2. College: 2

3. Graduate: 3

In [6]:
##Ordinal encoding
from sklearn.preprocessing import OrdinalEncoder

In [7]:
##Create a Sample DataFrame with an ordinal variable
df=pd.DataFrame({
    'size':['small','medium','large','medium','small','large']
})

In [8]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [ ]:
##Creating an instance variable in ordinal encoding
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [ ]:
##Performing fit_transform and transform
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [12]:
encoder.transform([['small']])

c:\Users\amitk\OneDrive\Desktop\complete data analyst bootcamp\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])